# Generated by Django 5.2.6 on 2025-09-27 17:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ATA', 'Ata de Reunião'), ('ATO', 'Ato Administrativo')], max_length=3)),
                ('data', models.DateField(default=datetime.date.today)),
                ('responsavel', models.CharField(max_length=255, verbose_name='Secretário(a) ou Responsável')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Ata ou Ato',
                'verbose_name_plural': 'Atas ou Atos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('regular', 'Regular'), ('avancada', 'Avançada'), ('lideranca', 'Liderança')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('AM', 'Artes e Habilidades Manuais'), ('AA', 'Atividades Agrícolas'), ('AR', 'Atividades Recreativas'), ('AP', 'Atividades Profissionais'), ('CS', 'Ciência e Saúde'), ('EN', 'Estudos da Natureza'), ('HD', 'Habilidades Domésticas'), ('ME', 'Mestrados')], max_length=2)),
                ('requisitos', models.FileField(blank=True, null=True, upload_to='especialidades/')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cargo', models.CharField(choices=[('DIR', 'Diretor'), ('ASCM', 'Diretor Associado'), ('ASCF', 'Diretora Associada'), ('SEC', 'Secretário(a)'), ('TES', 'Tesoureiro(a)'), ('CONS', 'Conselheiro(a)'), ('CSAS', 'Conselheiro(a) Associado(a)'), ('CAPC', 'Capelão(a) do Clube'), ('CAPU', 'Capitão(a) de Unidade'), ('SECU', 'Secretário(a) de Unidade'), ('TESU', 'Tesoureiro(a) de Unidade'), ('CAPUN', 'Capelão(a) de Unidade'), ('DBV', 'Desbravador(a)')], max_length=5)),
                ('data_nascimento', models.DateField()),
                ('nome_responsavel', models.CharField(blank=True, max_length=255)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=15)),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('classe_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desbravadores_na_classe', to='cadastros.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Transações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculina'), ('F', 'Feminina')], max_length=1, verbose_name='Sexo da Unidade')),
                ('grito_de_guerra', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('desbravador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fichamedica', serialize=False, to='cadastros.membro')),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NI', 'Não Informado')], default='NI', max_length=3, verbose_name='Tipo Sanguíneo')),
                ('alergias', models.TextField(blank=True, help_text='Liste todas as alergias conhecidas (medicamentos, alimentos, etc.)')),
                ('medicamentos_uso_continuo', models.TextField(blank=True, verbose_name='Medicamentos de Uso Contínuo')),
                ('plano_de_saude', models.CharField(blank=True, max_length=100, verbose_name='Plano de Saúde (Nome e número)')),
                ('contato_emergencia_nome', models.CharField(max_length=255, verbose_name='Nome do Contato de Emergência')),
                ('contato_emergencia_telefone', models.CharField(max_length=20, verbose_name='Telefone do Contato de Emergência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Médicas Adicionais')),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacaoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=255, verbose_name='Evento ou Atividade')),
                ('documento', models.FileField(upload_to='autorizacoes/', verbose_name='Documento Assinado')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('desbravador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to='cadastros.membro')),
            ],
            options={
                'verbose_name': 'Autorização de Saída',
                'verbose_name_plural': 'Autorizações de Saída',
                'ordering': ['-evento'],
            },
        ),
        migrations.CreateModel(
            name='MembroClasseConquistada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(default=datetime.date.today)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.classe')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.membro')),
            ],
            options={
                'verbose_name': 'Classe Conquistada',
                'verbose_name_plural': 'Classes Conquistadas',
                'unique_together': {('membro', 'classe')},
            },
        ),
        migrations.AddField(
            model_name='membro',
            name='classes_conquistadas',
            field=models.ManyToManyField(blank=True, related_name='concluintes', through='cadastros.MembroClasseConquistada', to='cadastros.classe'),
        ),
        migrations.CreateModel(
            name='MembroEspecialidadeConquistada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(default=datetime.date.today)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.especialidade')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.membro')),
            ],
            options={
                'verbose_name': 'Especialidade Concluída',
                'verbose_name_plural': 'Especialidades Concluídas',
                'unique_together': {('membro', 'especialidade')},
            },
        ),
        migrations.AddField(
            model_name='membro',
            name='especialidades_conquistadas',
            field=models.ManyToManyField(blank=True, through='cadastros.MembroEspecialidadeConquistada', to='cadastros.especialidade'),
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_estimado', models.DecimalField(decimal_places=2, help_text='Valor estimado por unidade', max_digits=10)),
                ('data_aquisicao', models.DateField(default=datetime.date.today)),
                ('responsavel', models.ForeignKey(blank=True, help_text='Membro responsável pelo Item (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.membro')),
            ],
            options={
                'verbose_name': 'Item do Patrimônio',
                'verbose_name_plural': 'Itens do Patrimônio',
                'ordering': ['item'],
            },
        ),
        migrations.AddField(
            model_name='membro',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.unidade'),
        ),
        migrations.CreateModel(
            name='PagamentoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desbravador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='cadastros.membro')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('desbravador', 'ano', 'mes')},
            },
        ),
    ]
